[package]
name = "connect-four"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]

[lib]
name = "minimax"
path = "src/lib.rs"

[dependencies]
text_io = "0.1.7"
fnv = "1.0.6"
gtk = "^0.3.0"
relm = "^0.11.0"
relm-derive = "^0.11.0"
