[package]
name = "connect-four"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]

[lib]
name = "minimax"
path = "src/lib.rs"

[profile.test]
opt-level = 3

[dependencies]
text_io = "0.1.7"
fnv = "1.0.6"
